--- 
deploy-to-aws-cloudfront: 
  docker: 
    - 
      image: "circleci/node:14.15.1"
  steps: 
    - checkout
    - 
      run: 
        command: "echo ${{CURRENT_BRANCH}}"
        name: "show current branch"
    - 
      run: 
        command: |
            sudo apt-get -y -qq update
            sudo apt-get install -y awscli
            sudo apt-get install -y python-pip python-dev build-essential
        name: "Installing AWS CLI"
        working_directory: /
    - 
      run: 
        command: |
            npm install
            npm run build
            cd build
            zip ../build.zip -r * .[^.]*
            echo "Build Successful"
        name: "Build Projects"
    - 
      run: 
        command: |
            aws configure set preview.cloudfront
            if [ "${CURRENT_BRANCH}" == "main" ]
            then
              aws cloudfront create-invalidation --distribution-id ${PRODUCTION_DISTRIBUTION_ID} --paths /\*
            elif [ "${CURRENT_BRANCH}" == "staging" ]
            then
              aws cloudfront create-invalidation --distribution-id ${STAGING_DISTRIBUTION_ID} --paths /\*
            else
              aws cloudfront create-invalidation --distribution-id ${DEV_DISTRIBUTION_ID} --paths /\*
            fi
        name: "Deploy to AWS Cloudfront"
  working_directory: ~/repo
deploy-to-aws-s3: 
  docker: 
    - 
      image: "circleci/node:14.15.1"
  steps: 
    - checkout
    - 
      run: 
        command: "echo ${{CURRENT_BRANCH}}"
        name: "show current branch"
    - 
      run: 
        command: |
            sudo apt-get -y -qq update
            sudo apt-get install -y awscli
            sudo apt-get install -y python-pip python-dev build-essential
        name: "Installing AWS CLI"
        working_directory: /
    - 
      run: 
        command: |
            npm install
            npm run build
            cd build
            zip ../build.zip -r * .[^.]*
            echo "Build Successful"
        name: "Build Projects"
    - 
      run: 
        command: |
            if [ "${CURRENT_BRANCH}" == "main" ]
            then
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_BUCKET_PRODUCTION} --delete
            elif [ "${CURRENT_BRANCH}" == "staging" ]
            then
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_BUCKET_STAGING} --delete
            else
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_DEV_BUCKET} --delete
            fi
        name: "Deploy to AWS S3"
  working_directory: ~/repo
jobs: 
  build: 
    docker: 
      - 
        image: "circleci/node:14.15.1"
    steps: 
      - checkout
      - 
        run: 
          command: "echo ${CURRENT_BRANCH}"
          name: "show current branch"
      - 
        restore_cache: 
          keys: 
            - "app-{{ checksum \"package.json\" }}"
            - app-
      - 
        run: 
          command: "npm install"
          name: "Install Dependencies"
      - 
        save_cache: 
          key: "app-{{ checksum \"package.json\" }}"
          paths: 
            - node_modules
    working_directory: ~/repo
version: 2.1
workflows: 
  build_and_deploy: 
    jobs: 
      - build
      - 
        deploy-to-aws-s3: ~
        filters: 
          branches: 
            only: 
              - develop
              - staging
              - main
        requires: 
          - build
      - 
        deploy-to-aws-cloudfront: ~
        filters: 
          branches: 
            only: 
              - develop
              - staging
              - main
        requires: 
          - deploy-to-aws-s3
